# This workflow runs pre-commit hooks on the files in the PR only.
#
# Author: Stefanie Molin

name: Check PR

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Run pre-commit checks on the files changed
  linting:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install

      - name: Run Checks
        run: |
          pre-commit run --from-ref origin/${{ github.base_ref }} --to-ref HEAD --show-diff-on-failure

  # Build and upload the docs for review
  docs:
    runs-on: ubuntu-latest
    name: Build docs

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install '.[docs]'

      - name: Sphinx build
        run: |
          cd docs
          make html

      - name: Upload built docs
        uses: actions/upload-artifact@v3
        with:
          name: docs-build-${{ github.sha }}
          path: docs/_build/html/dev/
          if-no-files-found: error
